ma

diff --git a/.github/workflows/fid.yml b/.github/workflows/fid.yml
--- a/.github/workflows/fid.yml
+++ b/.github/workflows/fid.yml
@@ -31,6 +31,16 @@ jobs:
           script: |
             mkdir -p /home/ubuntu/calculator
             cd /home/ubuntu/calculator
-            docker compose pull
-            docker compose up -d --build
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing..."
+              sudo apt update
+              sudo apt install -y docker.io docker-compose-plugin
+              sudo systemctl enable --now docker
+              sudo usermod -aG docker ubuntu
+              newgrp docker
+            fi
+              docker compose pull
+              docker compose up -d --build
+
+          
           
